name: Build Better Trakt

on:
  push:
    branches:
      - better-trakt
  pull_request:
    branches:
      - better-trakt
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Set up .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore Trakt.sln

      - name: Build
        run: dotnet build Trakt.sln --configuration Release --no-restore --warnaserror
