name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml@91aa56610cd3321f8897bbe2657c1743b3df3436 # master
    with:
      version: ${{ github.event.release.tag_name }}
      is-unstable: ${{ github.event.release.prerelease }}
    secrets:
      deploy-host: ${{ secrets.REPO_HOST }}
      deploy-user: ${{ secrets.REPO_USER }}
      deploy-key: ${{ secrets.REPO_KEY }}
